language: elm

script:
  - mkdir build
  - mkdir build/js
  - elm make --optimize --output=build/js/elm.js docs/src/Main.elm
  - cp docs/index.html build/index.html

deploy:
  - provider: script
    script: bash scripts/update-supported.sh
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
