jobs:
  include:
    - stage: test
      language: rust
      rust: stable
      cache: cargo
    - stage: docs
      language: elm
      elm:
        - latest-0.19.1
      elm_test: 0.19.1
      elm_format: 0.8.2
      if: branch = master
      cache:
        directories:
          - $HOME/.elm
      script:
        - mkdir build
        - mkdir build/js
        - cd docs
        - ./update-supported.sh
        - elm make --optimize --output=../build/js/elm.js src/Main.elm
        - cp index.html ../build/index.html

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master
