# This is a basic workflow to help you get started with Actions

name: elm-gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v2
      with:
        elm-version: 0.19.1
        
    - run: |
        cd docs
        ./update-supported.sh
        elm make --optimize --output=../build/js/elm.js src/Main.elm
        cp index.html ../build/index.html
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        build_dir: build
